# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0002_auto_20150312_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='last_harvest',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
