# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-06 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0003_collection_last_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='full_text',
            field=models.TextField(default=b''),
        ),
    ]
