# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('thumbnail_desc', models.CharField(blank=True, default='more...', max_length=160, null=True)),
                ('image', models.CharField(blank=True, default='icon.png', max_length=100L, verbose_name='Icon image file name')),
                ('listing_rank', models.IntegerField(blank=True, default=0, help_text='default rank. higher the number, lower the rank')),
                ('featured', models.BooleanField(default=False)),
                ('featured_rank', models.IntegerField(blank=True, default=0, help_text='higher the number, lower the rank')),
                ('headline', models.BooleanField(default=False)),
                ('headline_tag', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('private', models.BooleanField(default=False, help_text='checking this ON will require a user to login to view this story')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
