# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lltsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=255)),
                ('author_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('abstract', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('publish_date', models.DateTimeField()),
                ('department', models.CharField(max_length=512)),
                ('institution', models.CharField(max_length=512)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
