# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lltsite', '0002_dissertation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='abstract',
            field=models.TextField(default='', help_text='Raw text only please.'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='author',
            field=models.CharField(help_text='<first>, ... <last>', max_length=255),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='author_contact',
            field=models.EmailField(blank=True, help_text='(optional) email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='department',
            field=models.CharField(blank=True, help_text='(optional)', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='institution',
            field=models.CharField(help_text='University that awarded the dissertation.', max_length=512),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='keywords',
            field=models.TextField(default='', help_text='Enter 1 or more terms. Separate terms by a comma.'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='publish_date',
            field=models.DateField(help_text='date of awarded dissertation'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='url',
            field=models.URLField(blank=True, help_text='(optional) url with access to the document.', null=True),
        ),
    ]
