# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lltsite', '0003_auto_20170720_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dissertation',
        ),
    ]
