# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-23 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lltsite', '0008_storypage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
