# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-24 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lltsite', '0009_auto_20180623_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('factor', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
