# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-24 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lltsite', '0010_impactfactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactfactor',
            name='year',
        ),
    ]
